config/routes.rb
Rails.application.routes.draw do
  get 'orders/order_confirmation'
  get 'orders/orders_open'

  get 'orders/teste'
  devise_for :users
  resources :users
  resources :orders

  root to: "orders#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [ :show, :edit, :update, :destroy, :order_confirmation ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  def order_confirmation
    @check = @order.update_columns(situacao: false)
    redirect_back(fallback_location: :back, notice: "Ordem concluida com sucesso!")
  end

  def orders_open

    @orders_open = Order.where(situacao:true).order(created_at: :desc)

  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    @order.situacao = "ANDAMENTO"

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:pedido, :valor, :descricao, :telefone_cliente, :nome_cliente, :prazo_conclusao, :situacao)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:senha, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>CP bike</title>

<link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="/css/sb-admin-2.css" rel="stylesheet">

<link
href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<% if current_user.present? %>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

<!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
<div class="sidebar-brand-icon rotate-n-15">
    <i class="fas fa-laugh-wink"></i>
</div>
<div class="sidebar-brand-text mx-3">Ordem de Serviço </div>
</a>

<!-- Divider -->
<hr class="sidebar-divider my-0">

      

<!-- Nav Item - Dashboard -->
<li class="nav-item">
<p class="nav-link mb-0 ">
    <i class="fas fa-fw fa-tachometer-alt "></i>
    <span class=""><%= link_to 'Nova Ordem', new_order_path ,class:"text-white"%></span>
</p>
</li>

<hr class="sidebar-divider my-0">

<li class="nav-item">
<p class="nav-link mb-0" >
    <i class="fa fa-th-list fa-tachometer-alt"></i>
    <span><%= link_to 'Serviços',orders_path ,class:"text-white"%></span></p>

</li>

<hr class="sidebar-divider my-0">

<li class="nav-item">
<p class="nav-link mb-0" >
    <i class="fas fa-users fa-tachometer-alt"></i>
    <span><%= link_to 'Serviços em aberto',orders_orders_open_path ,class:"text-white"%></span></p>

</li>


<hr class="sidebar-divider my-0">

<li class="nav-item">
<p class="nav-link mb-0" >
    <i class="fas fa-times fa-tachometer-alt"></i>
    <span><%= link_to "Sair",destroy_user_session_path, method: :delete,class:"text-white"%></span></p>

</li>

<hr class="sidebar-divider d-none d-md-block">

<!-- Nav Item - Pages Collapse Menu -->

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
<button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>



<!-- End of Sidebar -->

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

<!-- Main Content -->
<div id="content">

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%if current_user.present?%>
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_user.email%></span>
                <%end%>
               
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400 pl-1 p-3 "></i>
                    Logout
                
            </div>
        </li>
        
    </ul>

</nav>
<%end%>

<div class="col-lg-12 mb-auto mt-3" >
<% flash.each do |name, msg| %>
    <% if msg.present? and msg.is_a?(String)  %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
    <% end %>
<% end %>
</div>
<!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->

    <%= yield %>


</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<!-- Footer -->
<footer class="sticky-footer bg-white">
<div class="container my-auto">
    <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
    </div>
</div>
</footer>
<!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
<i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
<div class="modal-footer">
    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
    <a class="btn btn-primary" href="login.html">Logout</a>
    
</div>
</div>
</div>
</div>


<script type="text/javascript">

    var el = document.querySelector("#box");

    console.log(el)
<script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="/js/sb-admin-2.min.js"></script>







</body>

</html>

app/views/orders/_form.html.erb
<div class="container">
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <hr class="sidebar-divider my-0 mb-4">

<div class="x_content d-flex d-flex justify-content-center align-items-center flex-column">

  <div class="col-md-6 col-sm-6 form-group ">
    <%= form.label :valor %>
    <%= form.text_field :valor , class:"form-control" %>
  </div>


  <div class="col-md-6 col-sm-6 form-group ">
    <%= form.label :descricao %>
    <%= form.text_area :descricao , class:"form-control"%>
  </div>

  <div class="col-md-6 col-sm-6 form-group ">
    <%= form.label :telefone_cliente %>
    <%= form.text_field :telefone_cliente , class:"form-control"%>
  </div>

  <div class="col-md-6 col-sm-6 form-group ">
    <%= form.label :nome_cliente %>
    <%= form.text_field :nome_cliente, class:"form-control" %>
  </div>

  <div class="col-md-6 col-sm-6 form-group ">
    <%= form.label :prazo_conclusao %>
    <%= form.text_field :prazo_conclusao , class:"form-control"%>
  </div>  

  <% if  not @order.new_record?%>

   <div class="row col-md-6">
    <div class="col">
      <%= form.radio_button :situacao, 'true',autocomplete:"off" ,id:"danger-outlined",class:"btn-check", checked:true%>
      <%= form.label "Aberto", for:"danger-outlined",class:"btn btn-outline-danger   w-100 p-3 mt-3" %>
    </div>
    <div class="col">
      <%= form.radio_button :situacao, 'false',autocomplete:"off",id:"success-outlined",class:"btn-check" %>
      <%= form.label "Concluido", for:"success-outlined",class:"btn btn-outline-success w-100 p-3 mt-3" %>
    </div>
  </div>
  <%end%>

  <div class="actions col-md-6 mt-3 ">
    <%= form.submit 'Registrar', class:'btn btn-primary w-100 p-3'%>
  </div>
</div>
<% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editando ordem de serviço</h1>

<%= render 'form', order: @order %>

<div class="container d-flex align-itens center justify-content-center">
<%= link_to 'visualizar', @order, class:"btn" %> 
<%= link_to 'voltar', orders_path , class:"btn"%>

</div>

app/views/orders/index.html.erb
<%= javascript_pack_tag 'button', 'data-turbolinks-track': 'reload' %>

<h1 class ="mb-5">Serviços em andamento</h1>

<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Valor</th>
      <th>Descricao</th>
      <th>Telefone cliente</th>
      <th>Nome cliente</th>
      <th>Prazo conclusao</th>
      <th>Situacao</th>
      <th>Finalizar Serviço</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr class="">
        <td><%= order.id %></td>
        <td><%= order.valor %></td>
        <td><%= order.descricao %></td>
        <td><%= order.telefone_cliente %></td>
        <td><%= order.nome_cliente %></td>
        <td><%= order.prazo_conclusao %></td>
        <% if order.situacao == false%>
        

        <td style="color:rgb(17, 66, 26);background-color:rgb(53, 207, 25) !important;padding:10px;border-radius:10px;display:flex;align-itens:center;justify-content:center" class="emAndamento">Concluido</td>
        
        <%else%>
        <td style="color:rgb(85, 85, 18);background-color:rgb(186, 197, 28);border-radius:10px;display:flex;align-itens:center;justify-content:center" class="emAndamento">Andamento</td>
        <%end%>
        <td>
          <a href='https://api.whatsapp.com/send?1=pt_BR&phone=55<%= order.telefone_cliente %>&text=Serviço concluido venha buscar retirar seu equipamento em nossa loja"' class=' dropdown-item' target='_blank' >
            <i class="fab fa-whatsapp fa-sm fa-fw mr-2 text-gray-400"></i>
            Whatsapp
          </a>
         </td>
         <td> 
         <% if order.situacao != false%>
            <%= link_to orders_order_confirmation_path(id: order.id), class: "btn  btn-info btn-xs" do %>
              <i class="fas fa-check"></i>
            <% end %>
          <% end %>
          </td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Excluir', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div id="box" >
  <button id="button1">Botao 1</button>
  <button id="button2">Botao 2</button>
</div>



<script type="text/javascript">

    var elemento = document.getElementById('#box');

    console.log(el)
<script>

app/views/orders/new.html.erb
<h1 class="text-center">Nova Ordem</h1>

<%= render 'form', order: @order %>

app/views/orders/order_confirmation.js.erb
<% if @check %>
	var result = confirm('Você tem certeza?')
	if (result == true){
		alert("Serviço concluido")
		$("#order_<%= params[:id] %>").html("CONCLUIDO");
	}
<% end %>

app/views/orders/orders_open.html.erb
<h1 class ="mb-5">Serviços</h1>

<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Descricao</th>
      <th>Telefone cliente</th>
      <th>Nome cliente</th>
      <th>Prazo conclusao</th>
      <th>Situacao</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders_open.each do |order| %>
      <tr class="">
        <td><%= order.id %></td>
        <td><%= order.descricao %></td>
        <td><%= order.telefone_cliente %></td>
        <td><%= order.nome_cliente %></td>
        <td><%= order.prazo_conclusao %></td>
        <% if order.situacao == false%>
        <td style="color:rgb(17, 66, 26);background-color:rgb(53, 207, 25);padding:10px;border-radius:10px;display:flex;align-itens:center;justify-content:center" class="emAndamento">Concluido</td> 
        <%else%>
        <td style="color:rgb(85, 85, 18);background-color:rgb(186, 197, 28);border-radius:10px;display:flex;align-itens:center;justify-content:center" class="emAndamento">Andamento</td>
        <%end%>
        <td>
          <a href='https://api.whatsapp.com/send?1=pt_BR&phone=55<%= order.telefone_cliente %>&text=Serviço concluido venha buscar retirar seu equipamento em nossa loja"' class=' dropdown-item' target='_blank' >
            <i class="fab fa-whatsapp fa-sm fa-fw mr-2 text-gray-400"></i>
            Whatsapp
          </a>
         </td>
         <td> 
         <% if order.situacao != false%>
            <%= link_to orders_order_confirmation_path(id: order.id), remote: true, onclick: "", class: "btn  btn-info btn-xs" do %>
              <i class="fas fa-check"></i>
            <% end %>
          <% end %>
          </td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Excluir', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @order.id %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @order.valor %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @order.descricao %>
</p>

<p>
  <strong>Telefone cliente:</strong>
  <%= @order.telefone_cliente %>
</p>

<p>
  <strong>Nome cliente:</strong>
  <%= @order.nome_cliente %>
</p>

<p>
  <strong>Prazo conclusao:</strong>
  <%= @order.prazo_conclusao %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @order.situacao %>
</p>

<div class="">
<%= link_to 'visualizar', @order, class:"btn" %> 
<%= link_to 'voltar', orders_path , class:"btn"%>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Senha</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.senha %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Senha:</strong>
  <%= @user.senha %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>